version: '3.9'
services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    restart: unless-stopped

  nginx:
    image: nginx:${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NODE_PORT=${NODE_PORT}
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./frontend:/vesp/frontend
      - ./www:/vesp/www
    ports:
      - ${NGINX_HOST}:${NGINX_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mariadb

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION
        - PHP_XDEBUG
        - TIME_ZONE
    volumes:
      - ./.env:/vesp/.env
      - ./core:/vesp/core
      - ./www:/vesp/www
      - ./upload:/vesp/upload
      - ./tmp:/vesp/tmp
      - ./log:/vesp/log
      - ./frontend:/vesp/frontend
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mariadb
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    restart: unless-stopped
    working_dir: /vesp/core
    command: sh -c 'composer install --no-dev && composer db:migrate && cron && php-fpm'

  node:
    image: node:${NODE_VERSION}
    volumes:
      - ./.env:/vesp/.env
      - ./frontend:/vesp/frontend
    depends_on:
      - nginx
    network_mode: 'service:nginx'
    restart: unless-stopped
    working_dir: /vesp/frontend
    command: sh -c 'rm -rf /tmp/* && yarn && yarn build && node ./.output/server/index.mjs'

  redis:
    image: redis:${REDIS_VERSION}